sed -e "s/ISC/Isc/g" standard.bjt > standard.bjt.tmp && cat standard.bjt.tmp > standard.bjt
sed -e "s/IS/Is/g" standard.bjt > standard.bjt.tmp && cat standard.bjt.tmp > standard.bjt
sed -e "s/VAF/Vaf/g" standard.bjt > standard.bjt.tmp && cat standard.bjt.tmp > standard.bjt
sed -e "s/BF/Bf/g" standard.bjt > standard.bjt.tmp && cat standard.bjt.tmp > standard.bjt
sed -e "s/IKF/Ikf/g" standard.bjt > standard.bjt.tmp && cat standard.bjt.tmp > standard.bjt
sed -e "s/XTB/Xtb/g" standard.bjt > standard.bjt.tmp && cat standard.bjt.tmp > standard.bjt
sed -e "s/BR/Br/g" standard.bjt > standard.bjt.tmp && cat standard.bjt.tmp > standard.bjt
sed -e "s/CJC/Cjc/g" standard.bjt > standard.bjt.tmp && cat standard.bjt.tmp > standard.bjt
sed -e "s/CJE/Cje/g" standard.bjt > standard.bjt.tmp && cat standard.bjt.tmp > standard.bjt
sed -e "s/TR/Tr/g" standard.bjt > standard.bjt.tmp && cat standard.bjt.tmp > standard.bjt
sed -e "s/TF/Tf/g" standard.bjt > standard.bjt.tmp && cat standard.bjt.tmp > standard.bjt
sed -e "s/ITf/Itf/g" standard.bjt > standard.bjt.tmp && cat standard.bjt.tmp > standard.bjt
sed -e "s/VTf/Vtf/g" standard.bjt > standard.bjt.tmp && cat standard.bjt.tmp > standard.bjt
sed -e "s/XTf/Xtf/g" standard.bjt > standard.bjt.tmp && cat standard.bjt.tmp > standard.bjt
sed -e "s/RB/Rb/g" standard.bjt > standard.bjt.tmp && cat standard.bjt.tmp > standard.bjt
sed -e "s/RC/Rc/g" standard.bjt > standard.bjt.tmp && cat standard.bjt.tmp > standard.bjt
sed -e "s/RE/Re/g" standard.bjt > standard.bjt.tmp && cat standard.bjt.tmp > standard.bjt
sed -e "s/AF/Af/g" standard.bjt > standard.bjt.tmp && cat standard.bjt.tmp > standard.bjt
sed -e "s/CJS/Cjs/g" standard.bjt > standard.bjt.tmp && cat standard.bjt.tmp > standard.bjt
sed -e "s/EG/Eg/g" standard.bjt > standard.bjt.tmp && cat standard.bjt.tmp > standard.bjt
sed -e "s/FC/Fc/g" standard.bjt > standard.bjt.tmp && cat standard.bjt.tmp > standard.bjt
sed -e "s/IK/Ik/g" standard.bjt > standard.bjt.tmp && cat standard.bjt.tmp > standard.bjt
sed -e "s/IkR/Ikr/g" standard.bjt > standard.bjt.tmp && cat standard.bjt.tmp > standard.bjt
sed -e "s/IRb/Irb/g" standard.bjt > standard.bjt.tmp && cat standard.bjt.tmp > standard.bjt
sed -e "s/MJC/Mjc/g" standard.bjt > standard.bjt.tmp && cat standard.bjt.tmp > standard.bjt
sed -e "s/MJE/Mje/g" standard.bjt > standard.bjt.tmp && cat standard.bjt.tmp > standard.bjt
sed -e "s/MJS/Mjs/g" standard.bjt > standard.bjt.tmp && cat standard.bjt.tmp > standard.bjt
sed -e "s/NC/Nc/g" standard.bjt > standard.bjt.tmp && cat standard.bjt.tmp > standard.bjt
sed -e "s/NE/Ne/g" standard.bjt > standard.bjt.tmp && cat standard.bjt.tmp > standard.bjt
sed -e "s/NF/Nf/g" standard.bjt > standard.bjt.tmp && cat standard.bjt.tmp > standard.bjt
sed -e "s/NR/Nr/g" standard.bjt > standard.bjt.tmp && cat standard.bjt.tmp > standard.bjt
sed -e "s/PTf/Ptf/g" standard.bjt > standard.bjt.tmp && cat standard.bjt.tmp > standard.bjt
sed -e "s/RbM/Rbm/g" standard.bjt > standard.bjt.tmp && cat standard.bjt.tmp > standard.bjt
sed -e "s/VAR/Var/g" standard.bjt > standard.bjt.tmp && cat standard.bjt.tmp > standard.bjt
sed -e "s/VJC/Vjc/g" standard.bjt > standard.bjt.tmp && cat standard.bjt.tmp > standard.bjt
sed -e "s/VJE/Vje/g" standard.bjt > standard.bjt.tmp && cat standard.bjt.tmp > standard.bjt
sed -e "s/VJS/Vjs/g" standard.bjt > standard.bjt.tmp && cat standard.bjt.tmp > standard.bjt
sed -e "s/XCjc/Xcjc/g" standard.bjt > standard.bjt.tmp && cat standard.bjt.tmp > standard.bjt
sed -e "s/XTI/Xti/g" standard.bjt > standard.bjt.tmp && cat standard.bjt.tmp > standard.bjt

